name: npm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@miguelmoreba'

      # - name: Authenticate with the GitHub Package Registry
      #   run:
      #     echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
      #     ~/.npmrc
      
      - run: npm ci
      
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}