name: version

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run'
        default: false
        type: boolean

jobs:
  version:
    runs-on: ubuntu-latest
        
    permissions:
      contents: write
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DRYRUN: ${{ inputs.dryRun }}
      NODE_VERSION: 'lts/*'

    name: version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "whatever@whatever.com"

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@miguelmoreba'

      - run: npm ci

      - run: npx nx affected --target=version --parallel=1 --push

      # - name: Tag last-release
      #   if: ${{ env.DRYRUN == 'false' }}

      #   shell: bash
      #   run: git tag -f last-release

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: ${{ github.ref }}
      #     force: true
      #     tags: true
